---
# Run with ansible-playbook <filename> -k
#   (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Update Packages
      raw: (apt-get update && apt-get -y upgrade)

    - name: Install Python 3
      command: apt-get update && apt-get install python3-minimal -y --no-install-recommends
      args:
        creates: /usr/bin/python3

    - name: Remove Python 2
      command: apt-get remove -y python-minimal python2 && apt-get autoremove -y
      args:
        removes: /usr/bin/python2

    - name: Ubuntu authorized_keys
      authorized_key: user=ubuntu
                      exclusive=no
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
    - name: Root authorized_keys
      authorized_key: user=root
                      exclusive=no
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
    - name: COMMON | Set environment
      blockinfile:
        dest: /etc/environment
        block: |
          LC_ALL=en_US.UTF-8
          LANG=en_US.UTF-8
      register: newenv
    
    - block:
      - name: COMMON | Generate locales
        raw: locale-gen en_US.UTF-8

      - name: COMMON | Reconfigure locales
        raw: update-locale LANG=en_US.UTF-8
      # only run this task block when we've just changed /etc/environment
      when: newenv.changed
